### ISSUE TITLE
Update the Wiki Page Developer Resources.

### ISSUE THREAD

**Issue by marcelcaraciolo** [muricoca/crab#5]
Update the wiki page Developer Resources to help new contributors to the Crab.

**Comment by rodrigoalvesvieira** [comment]
Ée, junto com isso eu vou melhorar a apresentação do README, destacando o que é mais importante.

**Comment by marcelcaraciolo** [comment]
I've updated the wiki. Bruno check it out , review it and if it is ok please close the issue.
https://github.com/muricoca/crab/wiki/Developer-Resources
