### ISSUE TITLE
TYPO in Documentation

### ISSUE THREAD

**Issue by tkamishima** [muricoca/crab#83]
In section 2.1.5 of http://muricoca.github.com/crab/tutorial.html, sample code

```
>>> from crab.recommenders.knn import UserBasedRecommender
```

should be

```
>>> from scikits.crab.recommenders.knn import UserBasedRecommender
```

**Comment by marians** [comment]
Since this is several months old and still not fixed in the docs, I wonder whether crab is actually maintained.

**Comment by marians** [comment]
Well. Last commit is from March 2012, and now an issue is closed without comment, remaining unsolved. Not ideal.

**Comment by qige96** [comment]
This project seems not to be maintained any more. I suggest that you can use <a href="https://github.com/NicolasHug/Surprise">Surprise</a>. This is also a python recommender engine which is still alive.
